### ISSUE TITLE
layout du site

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/www#1]
layout vertical à la http://www.devoxx.be

Header : BreizhJUG      Home Team Partners
Zone 1 : carousel (logo breizhjug, conférences, etc)
Zone 2 : prochain événement image + détails
Zone 3 : événements précédents sous forme de slideshow horizontal
Zone 4 : What's up (flux twitter) et mailing list
Footer : contacts, legals, etc

**Comment by ndeloof** [comment]
5 points

**Comment by ndeloof** [comment]
- bonus 2 points

**Comment by nmorel** [comment]
Il y a quoi comme page autre que home au final ? La home comporte déjà l'équipe et les sponsors, vous voulez quand même une page dédiée ? Pour les speakers, on a un aperçu avec quelques uns (aléatoire ?) sur le home et une page avec tous ?

Pour le header, on pourrait avoir le home en menu déroulant qui permet d'accéder aux différentes portions de la page et ne mettre à côté que les liens menant à d'autres pages.
