### ISSUE TITLE
Evénements passés

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/www#4]
Proposer les événements passés sous forme de liste horizontale (cf http://www.devoxx.be "latest news") avec chargement progressif

**Comment by ndeloof** [comment]
4 points

**Comment by nmorel** [comment]
Je verrais bien un merge des événements passés et à venir sur le slider. Il suffirait de mettre les événements à venir en premier avec un style particulier, un encadré ou autre. Cela permettrait d'avoir plusieurs événements à venir programmés et on afficherait dans la zone prochain événement, l'événement le plus proche.

Et on pourrait ensuite réutiliser ce slider sur la page d'événement pour naviguer entre eux.

**Comment by ndeloof** [comment]
on a pas plusieurs événements programmés en parallèle, ce n'est donc pas vraiment un besoin
le but de la section "événement passés" est de diffuser les liens (vidéo, slides) et de montrer l'activité du JUG, cette section ne doit pas occuper plus de 50% de la place allouée au prochain événement

**Comment by ndeloof** [comment]
j'ai repris la zone "previous events" pour la rendre plus compacte et privilégier le "next event"

**Comment by nmorel** [comment]
Je ne pensais pas forcément parallèle mais 2 événements proches. Il y a eu la saison passée 2 événements la même semaine, lundi et jeudi de mémoire mais ça reste exceptionnel donc pas vraiment nécessaire effectivement.

Pour les événements passés et à venir, on affiche toutes les infos sur la home page ? Pas de page dédiée par événement plus détaillée ?

**Comment by ndeloof** [comment]
pas de page dédiée par événement (en tout cas pas à ce stade). On a pas forcément grand chose à y mettre de toute façon
