### ISSUE TITLE
page speakers

### ISSUE THREAD

**Issue by ndeloof** [BreizhJUG/www#6]
Les speakers du JUG sont gérés dans un document JSON
- prenom, nom, email, twitter
- photo
- bio
- talk

ils sont identifiés par (nom+prenom) et référencés par les données événement

la page affiche les speakers et permet une recherche
pour le design, on peut s'inspirer de la section "twitter" de http://www.devoxx.be

**Comment by ndeloof** [comment]
5 points

**Comment by nmorel** [comment]
Pour les talks associés, comme on n'a pas de page événement, on ne peut pas faire de lien. Il faut les afficher en entier dans la bulle ?

**Comment by ndeloof** [comment]
A défaut d'une page par événement, on pourrait avoir une page pour tous les événements, une simple stack de l'historique du JUG, en renvoyer à la bonne section

**Comment by breizhcamp** [comment]
Pour les talks associés à un speaker, on peux avoir une modal.

**Comment by ybonnel** [comment]
Quand je répond par mail, il me met en tant que breizhcamp....

**Comment by nmorel** [comment]
Les modal rendent bien sur mobile ? (ou on s'en fiche peut être des mobiles :)

**Comment by ybonnel** [comment]
Non ça rend pas bien...

**Comment by ndeloof** [comment]
Les mobiles ne sont pas vraiment la cible en effet.
mais je ne suis pas sur pour autant qu'un modal soit idéal.

**Comment by nmorel** [comment]
On pourrait ajouter la page des événements avec en plus des filtres nom/speakers. Comme ça on peut arriver depuis la page speakers avec juste les événements de ce speaker. On aurait juste un lien "Voir ces événements" dans la bulle speaker.

**Comment by ndeloof** [comment]
C'est une bonne idée le filtre speaker sur la page des événements
Si dans un premier temps on a une page des événements :)
